import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/app/providers";
import Header from "@/components/Layout/Header/Header";
import Footer from "@/components/Layout/Footer/Footer";
import Navbar from "@/components/Layout/Navbar/Navbar";

export const metadata: Metadata = {
  title: "SnapShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className="antialiased">
          <Header />
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
