import type { Metadata } from 'next';
import './globals.css';
import StoreProvider from '@/app/StoreProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Header from '@/components/Layout/Header/Header';
import Footer from '@/components/Layout/Footer/Footer';
import Navbar from '@/components/Layout/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'SnapShop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className="antialiased">
          <Header />
          <Navbar />
          {children}
          <Footer />
          <ToastContainer />
        </body>
      </StoreProvider>
    </html>
  );
}
